import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../../data/local/app_database.dart';
import '../../data/repositories/local_bill_repository.dart';
import '../../data/repositories/local_contribution_repository.dart';
import '../../data/repositories/local_debt_repository.dart';
import '../../data/repositories/local_insurance_repository.dart';
import '../../data/repositories/local_transaction_repository.dart';
import '../../data/repositories/transaction_repository.dart';
import 'notification_service.dart';
import 'streak_service.dart';
import 'weekly_recap_service.dart';

/// Preference keys for automation toggles.
class AutomationKeys {
  static const autoContributions = 'auto_generate_contributions';
  static const autoBills = 'bills_reminders_enabled';
  static const autoDebts = 'debt_reminders_enabled';
  static const autoInsurance = 'insurance_reminders_enabled';
  static const pushEnabled = 'push_notifications';
  static const morningSummary = 'morning_summary';
  static const dailyLogReminder = 'daily_log_reminder_enabled';
  static const contribSalary = 'contribution_salary';
  static const contribEmploymentType = 'contribution_employment_type';
}

/// Runs automation tasks at app startup based on user preferences stored in
/// SharedPreferences. Uses local-first repositories.
class AutomationService {
  AutomationService._();

  /// Call after Supabase is initialized and the user is authenticated.
  static Future<void> runOnAppStart() async {
    final user = Supabase.instance.client.auth.currentUser;
    if (user == null) return;

    final prefs = await SharedPreferences.getInstance();
    final client = Supabase.instance.client;
    final db = AppDatabase.instance;

    // ── Auto-generate monthly contributions ──────────────────────────────────
    // Only run when toggle is ON AND user has input salary/employment type.
    if (prefs.getBool(AutomationKeys.autoContributions) ?? false) {
      final salary = prefs.getDouble(AutomationKeys.contribSalary);
      final empType = prefs.getString(AutomationKeys.contribEmploymentType);
      if (salary != null && salary > 0 && empType != null && empType.isNotEmpty) {
        await _autoGenerateContributions(db, client);
      }
    }

    // ── Auto-generate pending transactions for bills ─────────────────────────
    if (prefs.getBool(AutomationKeys.autoBills) ?? true) {
      await _autoGenerateBillPendingTransactions(db, client);
      await _scheduleBillNotifications(db, client);
    }

    // ── Auto-generate pending transactions for insurance ─────────────────────
    if (prefs.getBool(AutomationKeys.autoInsurance) ?? true) {
      await _autoGenerateInsurancePendingTransactions(db, client);
      await _scheduleInsuranceNotifications(db, client);
    }

    // ── Auto-generate pending transactions for debts ────────────────────────
    if (prefs.getBool(AutomationKeys.autoDebts) ?? true) {
      await _autoGenerateDebtPendingTransactions(db, client);
      await _scheduleDebtNotifications(db, client);
    }

    // ── Schedule contribution reminders ──────────────────────────────────────
    if (prefs.getBool(AutomationKeys.autoContributions) ?? false) {
      await _scheduleContributionReminders(db, client);
    }

    // ── Schedule daily "Log Your Expenses" reminder ─────────────────────────
    if (prefs.getBool(AutomationKeys.dailyLogReminder) ?? true) {
      await _scheduleDailyLogReminder(db, client);
    }

    // ── Schedule weekly recap notification (Sunday 10 AM) ─────────────────
    await _scheduleWeeklyRecap(db, client);
  }

  // ── Contributions ──────────────────────────────────────────────────────────

  static Future<void> _autoGenerateContributions(AppDatabase db, SupabaseClient client) async {
    try {
      final repo = LocalContributionRepository(db, client);
      final now = DateTime.now();
      final currentPeriod = '${now.year}-${now.month.toString().padLeft(2, '0')}';

      final existing = await repo.getContributions(period: currentPeriod);
      final existingTypes = existing.map((c) => c.type).toSet();

      final allContribs = await repo.getContributions();
      if (allContribs.isEmpty) return;

      const types = ['sss', 'philhealth', 'pagibig'];
      for (final type in types) {
        if (existingTypes.contains(type)) continue;

        final latestOfType = allContribs.where((c) => c.type == type).toList();
        if (latestOfType.isEmpty) continue;

        final ref = latestOfType.first;
        await repo.createContribution(
          type: type,
          period: currentPeriod,
          monthlySalary: ref.monthlySalary,
          employeeShare: ref.employeeShare,
          employerShare: ref.employerShare,
          totalContribution: ref.totalContribution,
          employmentType: ref.employmentType,
          notes: 'Auto-generated from previous month',
        );
      }
    } catch (e) {
      if (kDebugMode) debugPrint('AutomationService: contribution generation failed: $e');
    }
  }

  // ── Bill pending transaction auto-generation ──────────────────────────────

  static Future<void> _autoGenerateBillPendingTransactions(AppDatabase db, SupabaseClient client) async {
    try {
      final billRepo = LocalBillRepository(db, client);
      final txnRepo = LocalTransactionRepository(db, client);
      final bills = await billRepo.getBills();
      final now = DateTime.now();
      final monthTag = '${now.year}-${now.month.toString().padLeft(2, '0')}';

      // Fetch all transactions once to check for duplicates (avoid N+1 queries)
      final allTransactions = await txnRepo.getTransactions();

      for (final bill in bills) {
        if (!bill.isActive) continue;

        // Check billing cycle
        if (!_shouldGenerateForPeriod(
          billingCycle: bill.billingCycle,
          currentMonth: now.month,
        )) continue;

        // Skip if already paid this month
        if (bill.lastPaidDate != null) {
          final paid = DateTime.tryParse(bill.lastPaidDate!);
          if (paid != null && paid.year == now.year && paid.month == now.month) continue;
        }

        // Create a pending transaction for the bill
        final pendingDesc = '${bill.name} - $monthTag';
        // Check if pending transaction already exists (avoid duplicates)
        final alreadyExists = allTransactions.any((t) =>
            t.description == pendingDesc && t.isPending && t.category == bill.category);
        if (alreadyExists) continue;

        await txnRepo.createTransaction(
          amount: -bill.amount,
          category: bill.category,
          description: pendingDesc,
          date: DateTime.now(),
          status: 'pending',
          tags: ['bill', bill.id],
        );
      }
    } catch (e) {
      if (kDebugMode) debugPrint('AutomationService: bill pending transactions failed: $e');
    }
  }

  // ── Insurance pending transaction auto-generation ─────────────────────────

  static Future<void> _autoGenerateInsurancePendingTransactions(AppDatabase db, SupabaseClient client) async {
    try {
      final insRepo = LocalInsuranceRepository(db, client);
      final txnRepo = LocalTransactionRepository(db, client);
      final policies = await insRepo.getPolicies();
      final now = DateTime.now();
      final monthTag = '${now.year}-${now.month.toString().padLeft(2, '0')}';

      // Fetch all transactions once to check for duplicates (avoid N+1 queries)
      final allTransactions = await txnRepo.getTransactions();

      for (final policy in policies) {
        if (!policy.isActive) continue;

        // Check premium frequency
        if (!_shouldGenerateForPeriod(
          billingCycle: policy.premiumFrequency,
          currentMonth: now.month,
        )) continue;

        // Create a pending transaction for the insurance premium
        final pendingDesc = '${policy.name} premium - $monthTag';
        final alreadyExists = allTransactions.any((t) =>
            t.description == pendingDesc && t.isPending && t.category == 'Insurance');
        if (alreadyExists) continue;

        await txnRepo.createTransaction(
          amount: -policy.premiumAmount,
          category: 'Insurance',
          description: pendingDesc,
          date: DateTime.now(),
          status: 'pending',
          tags: ['insurance', policy.id],
        );
      }
    } catch (e) {
      if (kDebugMode) debugPrint('AutomationService: insurance pending transactions failed: $e');
    }
  }

  // ── Debt pending transaction auto-generation ──────────────────────────────

  static Future<void> _autoGenerateDebtPendingTransactions(AppDatabase db, SupabaseClient client) async {
    try {
      final debtRepo = LocalDebtRepository(db, client);
      final txnRepo = LocalTransactionRepository(db, client);
      final debts = await debtRepo.getDebts();
      final now = DateTime.now();
      final monthTag = '${now.year}-${now.month.toString().padLeft(2, '0')}';

      // Fetch all transactions once to check for duplicates (avoid N+1 queries)
      final allTransactions = await txnRepo.getTransactions();

      for (final debt in debts) {
        if (debt.isPaidOff) continue;

        final pendingDesc = '${debt.name} payment - $monthTag';
        final alreadyExists = allTransactions.any((t) =>
            t.description == pendingDesc && t.isPending && t.category == 'Debt Payment');
        if (alreadyExists) continue;

        await txnRepo.createTransaction(
          amount: -debt.minimumPayment,
          category: 'Debt Payment',
          description: pendingDesc,
          date: DateTime.now(),
          status: 'pending',
          tags: ['debt', debt.id],
        );
      }
    } catch (e) {
      if (kDebugMode) debugPrint('AutomationService: debt pending transactions failed: $e');
    }
  }

  // ── Helper: determine if a billing cycle requires an entry this period ──────

  static bool _shouldGenerateForPeriod({
    required String billingCycle,
    required int currentMonth,
  }) {
    switch (billingCycle) {
      case 'monthly':
        return true;
      case 'quarterly':
        return currentMonth % 3 == 1;
      case 'semi_annual':
        return currentMonth == 1 || currentMonth == 7;
      case 'annual':
        return currentMonth == 1;
      default:
        return true;
    }
  }

  // ── Generic payment reminder scheduler ─────────────────────────────────

  static Future<void> _schedulePaymentReminders({
    required String idPrefix,
    required String title,
    required double amount,
    required DateTime dueDate,
  }) async {
    final baseId = idPrefix.hashCode;

    await NotificationService.instance.scheduleNotification(
      id: baseId,
      title: 'Upcoming: $title',
      body: '$title payment of ${_fmt(amount)} due in 3 days',
      scheduledDate: dueDate.subtract(const Duration(days: 3)),
    );
    await NotificationService.instance.scheduleNotification(
      id: baseId + 1,
      title: 'Tomorrow: $title',
      body: '$title payment of ${_fmt(amount)} due tomorrow',
      scheduledDate: dueDate.subtract(const Duration(days: 1)),
    );
    await NotificationService.instance.scheduleNotification(
      id: baseId + 2,
      title: 'Due Today: $title',
      body: '$title payment of ${_fmt(amount)} is due today',
      scheduledDate: dueDate,
    );
  }

  /// Compute the next due date for a given due-day-of-month.
  static DateTime _nextDueDate(int dueDay) {
    final now = DateTime.now();
    final today = DateTime(now.year, now.month, now.day);
    final lastDay = DateTime(now.year, now.month + 1, 0).day;
    final clampedDay = dueDay.clamp(1, lastDay);
    var dueDate = DateTime(now.year, now.month, clampedDay);
    if (dueDate.isBefore(today)) {
      final nextLastDay = DateTime(now.year, now.month + 2, 0).day;
      dueDate = DateTime(now.year, now.month + 1, clampedDay.clamp(1, nextLastDay));
    }
    return dueDate;
  }

  // ── Bill notifications ────────────────────────────────────────────────────

  static Future<void> _scheduleBillNotifications(AppDatabase db, SupabaseClient client) async {
    try {
      final repo = LocalBillRepository(db, client);
      final bills = await repo.getBills();

      for (final bill in bills) {
        if (!bill.isActive || bill.dueDay == null) continue;
        final dueDate = _nextDueDate(bill.dueDay!);
        await _schedulePaymentReminders(
          idPrefix: 'bill-${bill.id}',
          title: bill.name,
          amount: bill.amount,
          dueDate: dueDate,
        );
      }
    } catch (e) {
      if (kDebugMode) debugPrint('AutomationService: bill notifications failed: $e');
    }
  }

  // ── Debt notifications ────────────────────────────────────────────────────

  static Future<void> _scheduleDebtNotifications(AppDatabase db, SupabaseClient client) async {
    try {
      final repo = LocalDebtRepository(db, client);
      final debts = await repo.getDebts();

      for (final debt in debts) {
        if (debt.isPaidOff || debt.dueDay == null) continue;
        final dueDate = _nextDueDate(debt.dueDay!);
        await _schedulePaymentReminders(
          idPrefix: 'debt-${debt.id}',
          title: debt.name,
          amount: debt.minimumPayment,
          dueDate: dueDate,
        );
      }
    } catch (e) {
      if (kDebugMode) debugPrint('AutomationService: debt notifications failed: $e');
    }
  }

  // ── Insurance notifications ───────────────────────────────────────────────

  static Future<void> _scheduleInsuranceNotifications(AppDatabase db, SupabaseClient client) async {
    try {
      final repo = LocalInsuranceRepository(db, client);
      final policies = await repo.getPolicies();
      final now = DateTime.now();
      final today = DateTime(now.year, now.month, now.day);

      for (final policy in policies) {
        if (!policy.isActive || policy.renewalDate == null) continue;

        final renewal = DateTime.tryParse(policy.renewalDate!);
        if (renewal == null) continue;

        final daysUntil = renewal.difference(today).inDays;
        if (daysUntil < -1 || daysUntil > 30) continue;

        await _schedulePaymentReminders(
          idPrefix: 'insurance-${policy.id}',
          title: policy.name,
          amount: policy.premiumAmount,
          dueDate: renewal,
        );
      }
    } catch (e) {
      if (kDebugMode) debugPrint('AutomationService: insurance notifications failed: $e');
    }
  }

  // ── Contribution reminders (3 days before month end, 1 day, last day) ─────

  static Future<void> _scheduleContributionReminders(AppDatabase db, SupabaseClient client) async {
    try {
      final repo = LocalContributionRepository(db, client);
      final now = DateTime.now();
      final currentPeriod = '${now.year}-${now.month.toString().padLeft(2, '0')}';
      final existing = await repo.getContributions(period: currentPeriod);
      final hasUnpaid = existing.any((c) => !c.isPaid);

      if (!hasUnpaid) return;

      final lastDayOfMonth = DateTime(now.year, now.month + 1, 0);
      final baseId = 'contrib-$currentPeriod'.hashCode;

      await NotificationService.instance.scheduleNotification(
        id: baseId,
        title: 'Contribution Reminder',
        body: 'Government contributions for $currentPeriod due in 3 days',
        scheduledDate: lastDayOfMonth.subtract(const Duration(days: 3)),
      );
      await NotificationService.instance.scheduleNotification(
        id: baseId + 1,
        title: 'Contribution Reminder',
        body: 'Government contributions for $currentPeriod due tomorrow',
        scheduledDate: lastDayOfMonth.subtract(const Duration(days: 1)),
      );
      await NotificationService.instance.scheduleNotification(
        id: baseId + 2,
        title: 'Contribution Due Today',
        body: 'Government contributions for $currentPeriod are due today',
        scheduledDate: lastDayOfMonth,
      );
    } catch (e) {
      if (kDebugMode) debugPrint('AutomationService: contribution reminders failed: $e');
    }
  }

  // ── Daily "Log Your Expenses" reminder at 7 PM Manila time ─────────────

  /// Tags that indicate an auto-generated (non-manual) transaction.
  static const _autoTags = {'auto-generated', 'bill', 'debt', 'insurance', 'contribution'};

  static Future<void> _scheduleDailyLogReminder(AppDatabase db, SupabaseClient client) async {
    try {
      final txnRepo = LocalTransactionRepository(db, client);
      final now = DateTime.now();
      final todayStr = '${now.year}-${now.month.toString().padLeft(2, '0')}-${now.day.toString().padLeft(2, '0')}';

      // Query today's confirmed transactions
      final todayTxns = await txnRepo.getTransactions(TransactionFilters(
        startDate: DateTime(now.year, now.month, now.day),
        endDate: DateTime(now.year, now.month, now.day),
      ));

      // Check if any are manual (confirmed, no auto-generated tags)
      final hasManualToday = todayTxns.any((t) {
        if (!t.isConfirmed) return false;
        final tags = t.tags ?? [];
        return !tags.any((tag) => _autoTags.contains(tag.toLowerCase()));
      });

      // If user already logged manual transactions today, skip
      if (hasManualToday) return;

      // Schedule notification at 7:00 PM Manila time today
      final target = DateTime(now.year, now.month, now.day, 19, 0);

      // Only schedule if 7 PM hasn't passed yet
      if (target.isAfter(now)) {
        final notifId = 'daily-log-$todayStr'.hashCode;

        // Include streak info in the notification body
        final streak = await StreakService.instance.getStreak();
        String body;
        if (streak >= 3) {
          body = "You're on a $streak-day streak! Don't break it. Log your expenses now.";
        } else if (streak == 0) {
          body = "Start a new streak today! Log your expenses to stay on top of your finances.";
        } else {
          body = "Don't forget to log your expenses! Track your spending to stay on top of your finances.";
        }

        await NotificationService.instance.scheduleNotification(
          id: notifId,
          title: 'Log Your Expenses',
          body: body,
          scheduledDate: target,
        );
      }
    } catch (e) {
      if (kDebugMode) debugPrint('AutomationService: daily log reminder failed: $e');
    }
  }

  // ── Weekly Recap notification (Sunday 10 AM Manila time) ─────────────────

  static Future<void> _scheduleWeeklyRecap(AppDatabase db, SupabaseClient client) async {
    try {
      final now = DateTime.now();
      // Find next Sunday
      final daysUntilSunday = (DateTime.sunday - now.weekday) % 7;
      final nextSunday = DateTime(now.year, now.month, now.day + daysUntilSunday, 10, 0);

      // Only schedule if it's in the future
      if (nextSunday.isBefore(now)) return;

      final recap = await WeeklyRecapService.instance.getWeeklyRecap();
      if (recap == null) return;

      final net = recap.saved;
      final body = net >= 0
          ? 'You saved ${_fmt(net)} this week!'
          : 'You spent ${_fmt(net.abs())} more than you earned this week.';

      final notifId = 'weekly-recap-${now.year}-${_weekNumber(now)}'.hashCode;
      await NotificationService.instance.scheduleNotification(
        id: notifId,
        title: 'Your Week in Review',
        body: body,
        scheduledDate: nextSunday,
      );
    } catch (e) {
      if (kDebugMode) debugPrint('AutomationService: weekly recap notification failed: $e');
    }
  }

  static int _weekNumber(DateTime d) {
    final dayOfYear = d.difference(DateTime(d.year, 1, 1)).inDays;
    return ((dayOfYear - d.weekday + 10) / 7).floor();
  }

  static String _fmt(double amount) => 'PHP ${amount.toStringAsFixed(2)}';
}
