import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:sandalan/data/local/app_database.dart';

/// Integration test: transaction creation updates account balance atomically.
/// Uses an in-memory Drift database — no Supabase, no file system.
void main() {
  late AppDatabase db;
  const userId = 'test-user-123';

  setUp(() async {
    SharedPreferences.setMockInitialValues({});
    // In-memory SQLite database for testing
    final connection = DatabaseConnection(NativeDatabase.memory());
    AppDatabase.initWith(connection);
    db = AppDatabase.instance;
    // Create tables
    await db.connection.executor.ensureOpen(DriftDatabaseUser());

    // Seed an account
    await db.upsertAccount({
      'id': 'acct-1',
      'user_id': userId,
      'name': 'GCash',
      'type': 'e-wallet',
      'currency': 'PHP',
      'balance': 10000.0,
      'is_archived': 0,
      'sync_status': 'synced',
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    });
  });

  group('Transaction → Account Balance', () {
    test('expense deducts from account balance', () async {
      // Create expense transaction
      await db.upsertTransaction({
        'id': 'txn-1',
        'user_id': userId,
        'amount': -500.0,
        'category': 'Food',
        'description': 'Jollibee',
        'date': '2026-03-30',
        'currency': 'PHP',
        'account_id': 'acct-1',
        'status': 'confirmed',
        'sync_status': 'pending',
        'created_at': DateTime.now().toIso8601String(),
        'updated_at': DateTime.now().toIso8601String(),
      });

      // Simulate _updateAccountBalance
      final acct = await db.getRowById('local_accounts', 'acct-1');
      expect(acct, isNotNull);
      final newBalance = (acct!['balance'] as num).toDouble() + (-500.0);
      acct['balance'] = newBalance;
      acct['sync_status'] = 'pending';
      await db.upsertAccount(acct);

      // Verify
      final updated = await db.getRowById('local_accounts', 'acct-1');
      expect(updated!['balance'], closeTo(9500.0, 0.01));
      expect(updated['sync_status'], 'pending');
    });

    test('income adds to account balance', () async {
      await db.upsertTransaction({
        'id': 'txn-2',
        'user_id': userId,
        'amount': 25000.0,
        'category': 'Salary',
        'description': 'March salary',
        'date': '2026-03-30',
        'currency': 'PHP',
        'account_id': 'acct-1',
        'status': 'confirmed',
        'sync_status': 'pending',
        'created_at': DateTime.now().toIso8601String(),
        'updated_at': DateTime.now().toIso8601String(),
      });

      final acct = await db.getRowById('local_accounts', 'acct-1');
      acct!['balance'] = (acct['balance'] as num).toDouble() + 25000.0;
      acct['sync_status'] = 'pending';
      await db.upsertAccount(acct);

      final updated = await db.getRowById('local_accounts', 'acct-1');
      expect(updated!['balance'], closeTo(35000.0, 0.01));
    });

    test('transaction sync_status is pending after creation', () async {
      await db.upsertTransaction({
        'id': 'txn-3',
        'user_id': userId,
        'amount': -100.0,
        'category': 'Transport',
        'description': 'Grab',
        'date': '2026-03-30',
        'currency': 'PHP',
        'account_id': 'acct-1',
        'status': 'confirmed',
        'sync_status': 'pending',
        'created_at': DateTime.now().toIso8601String(),
        'updated_at': DateTime.now().toIso8601String(),
      });

      final txn = await db.getRowById('local_transactions', 'txn-3');
      expect(txn!['sync_status'], 'pending');

      // Pending rows should be found by sync
      final pending = await db.getPendingRows('local_transactions');
      expect(pending.any((r) => r['id'] == 'txn-3'), true);
    });

    test('account balance update also marks account as pending', () async {
      final acct = await db.getRowById('local_accounts', 'acct-1');
      acct!['balance'] = (acct['balance'] as num).toDouble() - 200.0;
      acct['sync_status'] = 'pending';
      await db.upsertAccount(acct);

      final pendingAccounts = await db.getPendingRows('local_accounts');
      expect(pendingAccounts.any((r) => r['id'] == 'acct-1'), true);
    });
  });

  group('Confirm Payment → Multi-table Update', () {
    test('confirming pending transaction updates status + account', () async {
      // Create pending transaction (auto-generated by bill/debt automation)
      await db.upsertTransaction({
        'id': 'txn-pending',
        'user_id': userId,
        'amount': -3000.0,
        'category': 'Housing',
        'description': 'Meralco bill',
        'date': '2026-03-30',
        'currency': 'PHP',
        'account_id': null,
        'status': 'pending',
        'sync_status': 'pending',
        'tags': '["bill","bill-123"]',
        'created_at': DateTime.now().toIso8601String(),
        'updated_at': DateTime.now().toIso8601String(),
      });

      // Simulate confirmTransaction
      final existing = await db.getRowById('local_transactions', 'txn-pending');
      expect(existing!['status'], 'pending');

      final updated = Map<String, dynamic>.from(existing);
      updated['status'] = 'confirmed';
      updated['account_id'] = 'acct-1';
      updated['sync_status'] = 'pending';
      await db.upsertTransaction(updated);

      // Deduct from account
      final acct = await db.getRowById('local_accounts', 'acct-1');
      acct!['balance'] = (acct['balance'] as num).toDouble() + (-3000.0);
      acct['sync_status'] = 'pending';
      await db.upsertAccount(acct);

      // Verify transaction is confirmed
      final confirmedTxn = await db.getRowById('local_transactions', 'txn-pending');
      expect(confirmedTxn!['status'], 'confirmed');
      expect(confirmedTxn['account_id'], 'acct-1');

      // Verify account deducted
      final updatedAcct = await db.getRowById('local_accounts', 'acct-1');
      expect(updatedAcct!['balance'], closeTo(7000.0, 0.01));

      // Both should be pending for sync
      expect(confirmedTxn['sync_status'], 'pending');
      expect(updatedAcct['sync_status'], 'pending');
    });
  });

  group('Budget Category Matching', () {
    test('budget stored lowercase matches transaction lowercase', () async {
      // Budget stored as lowercase (as createBudget does)
      await db.upsertBudget({
        'id': 'budget-1',
        'user_id': userId,
        'category': 'food', // lowercase
        'amount': 5000.0,
        'month': '2026-03-01',
        'period': 'monthly',
        'rollover': 0,
        'sync_status': 'synced',
        'created_at': DateTime.now().toIso8601String(),
        'updated_at': DateTime.now().toIso8601String(),
      });

      // Transaction with mixed case
      await db.upsertTransaction({
        'id': 'txn-food',
        'user_id': userId,
        'amount': -250.0,
        'category': 'Food', // uppercase F
        'description': 'Jollibee',
        'date': '2026-03-15',
        'currency': 'PHP',
        'account_id': 'acct-1',
        'status': 'confirmed',
        'sync_status': 'pending',
        'created_at': DateTime.now().toIso8601String(),
        'updated_at': DateTime.now().toIso8601String(),
      });

      // Simulate the planning_tab matching logic
      final budgets = await db.getBudgets(userId, '2026-03-01', 'monthly');
      final transactions = await db.getTransactions(userId);

      final spentByCategory = <String, double>{};
      for (final t in transactions) {
        final amount = (t['amount'] as num).toDouble();
        if (amount >= 0) continue;
        final cat = (t['category'] as String).toLowerCase();
        spentByCategory[cat] = (spentByCategory[cat] ?? 0) + amount.abs();
      }

      // Budget category is 'food', transaction lowercased is 'food' — should match
      final budget = budgets.first;
      final spent = spentByCategory[budget['category'] as String] ?? 0;
      expect(spent, closeTo(250.0, 0.01));
    });
  });

  group('Salary Allocation → Budget Creation', () {
    test('budget exists check is case-insensitive', () async {
      // Existing budget with lowercase category (as stored by createBudget)
      await db.upsertBudget({
        'id': 'budget-existing',
        'user_id': userId,
        'category': 'food',
        'amount': 3000.0,
        'month': '2026-03-01',
        'period': 'monthly',
        'rollover': 0,
        'sync_status': 'synced',
        'created_at': DateTime.now().toIso8601String(),
        'updated_at': DateTime.now().toIso8601String(),
      });

      // Simulate salary allocation rule.label = 'Food' (mixed case)
      final ruleLabel = 'Food';
      final existingBudgets = await db.getBudgets(userId, '2026-03-01', 'monthly');

      // The fix: compare rule.label.toLowerCase() to budget.category
      final exists = existingBudgets.any(
          (b) => (b['category'] as String) == ruleLabel.toLowerCase());
      expect(exists, true, reason: 'Should find existing budget with case-insensitive match');
    });
  });

  group('Free Tier Limits', () {
    test('can create exactly 2 accounts', () async {
      // Account 1 already exists from setUp
      await db.upsertAccount({
        'id': 'acct-2',
        'user_id': userId,
        'name': 'BDO',
        'type': 'bank',
        'currency': 'PHP',
        'balance': 5000.0,
        'is_archived': 0,
        'sync_status': 'synced',
        'created_at': DateTime.now().toIso8601String(),
        'updated_at': DateTime.now().toIso8601String(),
      });

      // Query all accounts
      final accounts = await db.getAccounts(userId);
      expect(accounts.length, 2);

      // Free tier limit check (simulating UI logic)
      const freeAccountLimit = 2;
      final canCreateMore = accounts.length < freeAccountLimit;
      expect(canCreateMore, false, reason: 'Should be at limit');
    });

    test('can create exactly 3 budgets', () async {
      for (int i = 1; i <= 3; i++) {
        await db.upsertBudget({
          'id': 'budget-limit-$i',
          'user_id': userId,
          'category': 'cat$i',
          'amount': 1000.0,
          'month': '2026-03-01',
          'period': 'monthly',
          'rollover': 0,
          'sync_status': 'synced',
          'created_at': DateTime.now().toIso8601String(),
          'updated_at': DateTime.now().toIso8601String(),
        });
      }

      final budgets = await db.getBudgets(userId, '2026-03-01', 'monthly');
      expect(budgets.length, 3);

      const freeBudgetLimit = 3;
      final canCreateMore = budgets.length < freeBudgetLimit;
      expect(canCreateMore, false);
    });

    test('can create exactly 2 goals', () async {
      for (int i = 1; i <= 2; i++) {
        await db.upsertGoal({
          'id': 'goal-$i',
          'user_id': userId,
          'name': 'Goal $i',
          'target_amount': 10000.0,
          'current_amount': 0.0,
          'category': 'Savings',
          'is_completed': 0,
          'sync_status': 'synced',
          'created_at': DateTime.now().toIso8601String(),
          'updated_at': DateTime.now().toIso8601String(),
        });
      }

      final goals = await db.getGoals(userId);
      expect(goals.length, 2);

      const freeGoalLimit = 2;
      final canCreateMore = goals.length < freeGoalLimit;
      expect(canCreateMore, false);
    });
  });
}

/// Minimal implementation to satisfy Drift's ensureOpen requirement.
class DriftDatabaseUser extends QueryExecutorUser {
  @override
  int get schemaVersion => 1;

  @override
  Future<void> beforeOpen(QueryExecutor executor, OpeningDetails details) async {}
}
